CREATE TABLE `admin_action_logs` (
	`id` varchar(36) NOT NULL DEFAULT (UUID()),
	`admin_id` varchar(36) NOT NULL,
	`action_type` varchar(50) NOT NULL,
	`target_type` varchar(50) NOT NULL,
	`target_id` varchar(36) NOT NULL,
	`description` text,
	`changes` json,
	`reason` text,
	`ip_address` varchar(45),
	`user_agent` text,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `admin_action_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `system_config` (
	`id` varchar(36) NOT NULL DEFAULT (UUID()),
	`app_name` varchar(255) DEFAULT '深圳初高中错题分析学习系统',
	`app_version` varchar(50),
	`enable_user_registration` boolean DEFAULT true,
	`enable_social_sharing` boolean DEFAULT true,
	`enable_collaboration` boolean DEFAULT true,
	`enable_ai_analysis` boolean DEFAULT true,
	`max_upload_size` int DEFAULT 10,
	`max_questions_per_upload` int DEFAULT 100,
	`max_collaborators` int DEFAULT 10,
	`smtp_host` varchar(255),
	`smtp_port` int DEFAULT 587,
	`smtp_user` varchar(255),
	`smtp_password` text,
	`smtp_from_email` varchar(255),
	`sms_api_url` varchar(500),
	`sms_api_key` text,
	`maintenance_mode` boolean DEFAULT false,
	`maintenance_message` text,
	`config` json,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `system_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `system_health_checks` (
	`id` varchar(36) NOT NULL DEFAULT (UUID()),
	`database_status` varchar(20) DEFAULT 'healthy',
	`database_response_time` int,
	`api_response_time` int,
	`api_error_rate` int,
	`storage_usage` int,
	`storage_quota` int,
	`memory_usage` int,
	`cpu_usage` int,
	`active_users` int DEFAULT 0,
	`total_requests` int DEFAULT 0,
	`error_count` int DEFAULT 0,
	`status` varchar(20) DEFAULT 'healthy',
	`details` json,
	`checked_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `system_health_checks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_settings` (
	`id` varchar(36) NOT NULL DEFAULT (UUID()),
	`user_id` varchar(36) NOT NULL,
	`display_name` varchar(255),
	`avatar` text,
	`bio` text,
	`preferred_grades` json,
	`preferred_subjects` json,
	`preferred_difficulty_levels` json,
	`email_notifications` boolean DEFAULT true,
	`push_notifications` boolean DEFAULT true,
	`sms_notifications` boolean DEFAULT false,
	`notification_frequency` varchar(20) DEFAULT 'daily',
	`is_profile_public` boolean DEFAULT false,
	`allow_share_questions` boolean DEFAULT true,
	`allow_collaboration` boolean DEFAULT true,
	`theme` varchar(20) DEFAULT 'auto',
	`language` varchar(10) DEFAULT 'zh-CN',
	`auto_backup` boolean DEFAULT true,
	`backup_frequency` varchar(20) DEFAULT 'weekly',
	`review_reminder_enabled` boolean DEFAULT true,
	`review_reminder_time` varchar(5),
	`review_reminder_days` json DEFAULT JSON_ARRAY(),
	`daily_learning_goal` int DEFAULT 30,
	`weekly_learning_goal` int DEFAULT 180,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_settings_user_id_unique` UNIQUE(`user_id`)
);
